# Generated by Django 4.2.16 on 2024-12-11 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Server', 'Server'), ('Projector', 'Projector'), ('CCTV Camera', 'CCTV Camera')], max_length=20)),
                ('tag', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Asus', 'Asus'), ('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Microsoft', 'Microsoft'), ('MSI', 'MSI')], max_length=20)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('CheckedIn', 'CheckedIn'), ('CheckedOut', 'CheckedOut'), ('UnderService', 'UnderService'), ('Discarded', 'Discarded')], default='CheckedIn', max_length=20, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Hard Disk', 'Hard Disk'), ('SSD', 'SSD'), ('RAM', 'RAM'), ('Processor', 'Processor'), ('Motherboard', 'Motherboard'), ('PSU', 'PSU')], max_length=20)),
                ('tag', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(choices=[('Cooler Master', 'Cooler Master'), ('Crucial', 'Crucial'), ('DeepCool', 'DeepCool'), ('HP', 'HP'), ('Kingston', 'Kingston'), ('Samsung', 'Samsung'), ('WD', 'WD')], max_length=20)),
                ('purchase_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('request_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
